version: "3.7"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ${WEB_DIR}:/var/www/html/:rw
      - ${NGINX_CONFIG_DIR}:/etc/nginx/conf.d/:ro
      - ${NGINX_CONFIG_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_CERTS_DIR}:/etc/nginx/certs:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default
    command: nginx -g 'daemon off;'